
package br.com.maplink2.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Route", targetNamespace = "http://webservices.maplink2.com.br", wsdlLocation = "http://services.maplink.com.br/webservices/v3/route/route.asmx?wsdl")
public class Route
    extends Service
{

    private final static URL ROUTE_WSDL_LOCATION;
    private final static WebServiceException ROUTE_EXCEPTION;
    private final static QName ROUTE_QNAME = new QName("http://webservices.maplink2.com.br", "Route");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://services.maplink.com.br/webservices/v3/route/route.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROUTE_WSDL_LOCATION = url;
        ROUTE_EXCEPTION = e;
    }

    public Route() {
        super(__getWsdlLocation(), ROUTE_QNAME);
    }

    public Route(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROUTE_QNAME, features);
    }

    public Route(URL wsdlLocation) {
        super(wsdlLocation, ROUTE_QNAME);
    }

    public Route(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROUTE_QNAME, features);
    }

    public Route(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Route(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RouteSoap
     */
    @WebEndpoint(name = "RouteSoap")
    public RouteSoap getRouteSoap() {
        return super.getPort(new QName("http://webservices.maplink2.com.br", "RouteSoap"), RouteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RouteSoap
     */
    @WebEndpoint(name = "RouteSoap")
    public RouteSoap getRouteSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.maplink2.com.br", "RouteSoap"), RouteSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROUTE_EXCEPTION!= null) {
            throw ROUTE_EXCEPTION;
        }
        return ROUTE_WSDL_LOCATION;
    }

}
